# -*- coding: utf-8 -*-
"""Contenuti delle pagine Servizi e delle pagine per mestiere (3 lingue).
Regola: solo fatti gia' presenti sul sito; gli esempi numerici sono dichiarati "illustrativi".
Modificare qui, poi: python3 tools/build-landing.py"""

MAIL = "kharonte.appdev@gmail.com"

# ---------------------------------------------------------------- SERVIZI
SERVICES = {
 'it': dict(
  file='servizi.html', title="Sviluppo app e software su misura — Kharonte Studio",
  desc="App native iOS e Android, piattaforme web full-stack e integrazioni di IA da uno sviluppatore indipendente: dall'idea alla pubblicazione.",
  eyebrow="Sviluppo su misura", h1a="App e software su misura,", h1b="da chi li progetta e li pubblica.",
  sub="Lavoro da solo, con oltre 10 anni di esperienza: parli direttamente con chi disegna, sviluppa e porta il prodotto sugli store. App mobile, piattaforme web e intelligenza artificiale, dall'idea al lancio.",
  cta="Raccontami il progetto", cta2="Guarda le app pubblicate", subj="Progetto%20su%20misura", breadcrumb="Servizi",
  s1=("Cosa costruisco", "Tre ambiti, un unico responsabile.", [
     ("App mobile native", "Applicazioni per iOS e Android pensate per essere veloci e per funzionare anche senza connessione, con i dati sul dispositivo quando ha senso."),
     ("Piattaforme web full-stack", "Frontend reattivi e accessibili, backend con API sicure e database, progettati per crescere insieme al prodotto."),
     ("Intelligenza artificiale pratica", "Modelli linguistici, visione artificiale ed elaborazione semantica integrati nei flussi di lavoro, on-device o in cloud, solo dove portano un vantaggio concreto.")]),
  s2=("Come lavoro", "Dall'idea alla pubblicazione, senza passaggi di mano.", [
     ("Ascolto", "Si parte dal problema reale e da chi userà il prodotto, non da un elenco di funzioni."),
     ("Design e prototipo", "Schermate pensate per il gesto reale dell'utente, validate su un prototipo prima dello sviluppo."),
     ("Sviluppo e test", "Sviluppo nativo, test su dispositivi reali, attenzione a prestazioni e accessibilità."),
     ("Pubblicazione e assistenza", "Build, revisione degli store, scheda, screenshot e supporto dopo il lancio.")]),
  s3=("Lavori pubblicati", "Cinque prodotti, dall'interfaccia agli store.", "Le app dello studio mostrano come lavoro. Puoi provarne le demo direttamente nella home.",
     "In rilascio sugli store", "Vedi la scheda"),
  faq_label="Prima di scrivermi", faq_title="Domande frequenti",
  faq=[("Come si inizia?", "Scrivimi a %s con una breve descrizione del progetto, degli utenti a cui è destinato e delle scadenze: ti rispondo con i passi successivi." % MAIL),
       ("Lavori da solo?", "Sì. Kharonte Studio è uno studio indipendente di una sola persona: progettazione, sviluppo e pubblicazione passano da un unico referente."),
       ("Ti occupi anche della pubblicazione sugli store?", "Sì: build, revisione, scheda, screenshot e assistenza fanno parte del lavoro, come per le app dello studio."),
       ("Quanto costa un progetto?", "Dipende da portata e complessità: dopo una prima conversazione preparo una proposta per il tuo caso.")],
  ctat="Hai un progetto in mente?", ctad="Scrivimi: ti rispondo personalmente."),
 'en': dict(
  file='services.html', title="Custom App & Software Development — Kharonte Studio",
  desc="Native iOS and Android apps, full-stack web platforms and AI integrations from an independent developer: from idea to store release.",
  eyebrow="Custom development", h1a="Custom apps and software,", h1b="from the person who designs and ships them.",
  sub="I work solo, with 10+ years of experience: you talk directly to the person who designs, builds and takes the product to the stores. Mobile apps, web platforms and AI, from idea to launch.",
  cta="Tell me about your project", cta2="See the published apps", subj="Custom%20Project", breadcrumb="Services",
  s1=("What I build", "Three areas, one person in charge.", [
     ("Native mobile apps", "iOS and Android apps built to be fast and to work offline too, keeping data on the device where it makes sense."),
     ("Full-stack web platforms", "Responsive, accessible front ends and back ends with secure APIs and databases, designed to grow with the product."),
     ("Practical AI", "Language models, computer vision and semantic processing woven into real workflows, on-device or in the cloud, only where they bring a concrete benefit.")]),
  s2=("How I work", "From idea to release, with no hand-offs.", [
     ("Listening", "We start from the real problem and the people who will use the product, not from a feature list."),
     ("Design and prototype", "Screens designed around the user's real gesture, validated on a prototype before development."),
     ("Build and test", "Native development, testing on real devices, attention to performance and accessibility."),
     ("Release and support", "Build, store review, listing, screenshots and support after launch.")]),
  s3=("Published work", "Five products, from interface to the stores.", "The studio's own apps show how I work. You can try their demos right on the home page.",
     "Being released on the stores", "See details"),
  faq_label="Before you write", faq_title="Frequently asked questions",
  faq=[("How do we start?", "Write to %s with a short description of the project, its users and your deadlines: I'll reply with the next steps." % MAIL),
       ("Do you work alone?", "Yes. Kharonte Studio is an independent one-person studio: design, development and release all go through a single contact."),
       ("Do you also handle publishing on the app stores?", "Yes: build, review, listing, screenshots and support are part of the job, just as for the studio's own apps."),
       ("How much does a project cost?", "It depends on scope and complexity: after a first conversation I prepare a proposal for your case.")],
  ctat="Have a project in mind?", ctad="Write to me: I reply personally."),
 'es': dict(
  file='servicios.html', title="Desarrollo de apps y software a medida — Kharonte Studio",
  desc="Apps nativas iOS y Android, plataformas web full-stack e integraciones de IA de la mano de un desarrollador independiente: de la idea a las tiendas.",
  eyebrow="Desarrollo a medida", h1a="Apps y software a medida,", h1b="de quien los diseña y los publica.",
  sub="Trabajo en solitario, con más de 10 años de experiencia: hablas directamente con quien diseña, desarrolla y lleva el producto a las tiendas. Apps móviles, plataformas web e inteligencia artificial, de la idea al lanzamiento.",
  cta="Cuéntame tu proyecto", cta2="Ver las apps publicadas", subj="Proyecto%20Personalizado", breadcrumb="Servicios",
  s1=("Qué construyo", "Tres ámbitos, un único responsable.", [
     ("Apps móviles nativas", "Aplicaciones para iOS y Android pensadas para ser rápidas y funcionar también sin conexión, con los datos en el dispositivo cuando tiene sentido."),
     ("Plataformas web full-stack", "Frontends ágiles y accesibles, backends con APIs seguras y bases de datos, diseñados para crecer con el producto."),
     ("Inteligencia artificial práctica", "Modelos de lenguaje, visión artificial y procesamiento semántico integrados en los flujos de trabajo, en el dispositivo o en la nube, solo donde aportan una ventaja concreta.")]),
  s2=("Cómo trabajo", "De la idea a la publicación, sin traspasos.", [
     ("Escucha", "Se parte del problema real y de quien usará el producto, no de una lista de funciones."),
     ("Diseño y prototipo", "Pantallas pensadas para el gesto real del usuario, validadas en un prototipo antes de desarrollar."),
     ("Desarrollo y pruebas", "Desarrollo nativo, pruebas en dispositivos reales y atención al rendimiento y la accesibilidad."),
     ("Publicación y soporte", "Compilación, revisión de las tiendas, ficha, capturas y soporte tras el lanzamiento.")]),
  s3=("Trabajos publicados", "Cinco productos, de la interfaz a las tiendas.", "Las apps del estudio muestran cómo trabajo. Puedes probar sus demos directamente en la página de inicio.",
     "En proceso de lanzamiento en las tiendas", "Ver la ficha"),
  faq_label="Antes de escribirme", faq_title="Preguntas frecuentes",
  faq=[("¿Cómo se empieza?", "Escríbeme a %s con una breve descripción del proyecto, de sus usuarios y de tus plazos: te respondo con los siguientes pasos." % MAIL),
       ("¿Trabajas en solitario?", "Sí. Kharonte Studio es un estudio independiente de una sola persona: diseño, desarrollo y publicación pasan por un único interlocutor."),
       ("¿También te encargas de la publicación en las tiendas?", "Sí: compilación, revisión, ficha, capturas y soporte forman parte del trabajo, igual que en las apps del estudio."),
       ("¿Cuánto cuesta un proyecto?", "Depende del alcance y la complejidad: tras una primera conversación preparo una propuesta para tu caso.")],
  ctat="¿Tienes un proyecto en mente?", ctad="Escríbeme: te respondo personalmente."),
}

# apps (per elenco prove)
APPS = [
 ('preventivi-facili', 'Preventivi Facili', {'it': "Preventivi PDF in 30 secondi per artigiani e professionisti.", 'en': "PDF quotes in 30 seconds for tradespeople and freelancers.", 'es': "Presupuestos PDF en 30 segundos para profesionales y autónomos."}, True),
 ('foodlio', 'Foodlio', {'it': "Food cost, margini e menu engineering per ristoranti e bar.", 'en': "Food cost, margins and menu engineering for restaurants and bars.", 'es': "Food cost, márgenes e ingeniería de menú para restaurantes y bares."}, True),
 ('padel-match-manager', 'Padel Match Manager', {'it': "Tornei di padel Americano, Mexicano e gironi.", 'en': "Americano, Mexicano and round-robin padel tournaments.", 'es': "Torneos de pádel Americano, Mexicano y liguillas."}, True),
 ('aegis', 'Aegis', {'it': "Respirazione guidata, meditazioni e diario privato.", 'en': "Guided breathing, meditation and a private journal.", 'es': "Respiración guiada, meditaciones y diario privado."}, True),
 ('flipeven', 'FlipEven', {'it': "Punto di pareggio e guadagno netto per chi rivende.", 'en': "Break-even and net profit for resellers.", 'es': "Punto de equilibrio y ganancia neta para quien revende."}, False),
]

# ---------------------------------------------------------------- PAGINE PER MESTIERE
# parent: cartella dell'app; sub: sottocartella della pagina; body: classe di <body> copiata dalla pagina app
NICHES = {
 'elettricisti': dict(parent='preventivi-facili', sub='elettricisti', name='Preventivi Facili', icon='assets/icon.png',
  it=dict(
   title="Preventivi per Elettricisti — Preventivi Facili", desc="App per elettricisti: crea preventivi PDF professionali in 30 secondi dal telefono, con IVA, logo e firma. Funziona offline, senza canoni mensili.",
   eyebrow="PER ELETTRICISTI • PREVENTIVI IN PDF", h1a="Il preventivo elettrico,", h1b="pronto prima di lasciare il cantiere.",
   sub="Crea un preventivo PDF professionale in circa 30 secondi dal telefono, con IVA calcolata, il tuo logo e la firma. Funziona offline e i dati restano sul tuo dispositivo.",
   s1=("Pensato per chi lavora in cantiere", "Meno carta, meno sera passata al computer.", [
      ("Subito dopo il sopralluogo", "L'app genera il PDF e prepara un messaggio pronto: lo invii con WhatsApp, email o AirDrop mentre sei ancora dal cliente."),
      ("IVA e regimi fiscali", "Regime ordinario, forfettario o con cassa previdenziale: imponibile, imposte e totali vengono calcolati senza errori di conto."),
      ("Firma e timbro su ogni PDF", "Carichi una volta la tua firma o il timbro dell'azienda e compaiono su ogni preventivo, pronti per l'accettazione del cliente."),
      ("Rubrica clienti", "Richiami i dati di un cliente abituale con un tocco e compili il nuovo preventivo al volo."),
      ("Funziona anche senza rete", "Nei locali interrati o in cantiere non serve segnale: i dati restano sul tuo telefono e nessun preventivo finisce su server esterni."),
      ("Il tuo logo, il tuo stile", "Aggiungi logo e dati aziendali: il preventivo ha l'aspetto della tua attività.")]),
   ex=("Un esempio di voci", "Esempio illustrativo con importi di fantasia, non un listino.",
       ["Descrizione", "Q.tà", "Importo"],
       [("Quadro elettrico con magnetotermici", "1", "480,00 €"), ("Punti presa o luce", "8", "280,00 €"), ("Manodopera (ore)", "6", "228,00 €")],
       [("Imponibile", "988,00 €"), ("IVA 22%", "217,36 €"), ("Totale", "1.205,36 €")]),
   faq=[("Posso usarlo per più clienti e più cantieri?", "Sì. La rubrica clienti conserva i dati dei clienti abituali e li richiami con un tocco quando crei un nuovo preventivo."),
        ("I dati dei miei clienti sono al sicuro?", "L'app funziona con memorizzazione solo locale sul telefono: nessun server esterno raccoglie i nomi dei tuoi clienti o i tuoi listini."),
        ("Quanto costa?", "Puoi scaricarla gratis e creare i primi 3 preventivi. Per continuare c'è un acquisto singolo a vita, senza canoni mensili; il prezzo aggiornato è nello store."),
        ("Esiste una pagina per altri mestieri?", "Sì, c'è anche la pagina per idraulici; l'app è la stessa e vale per artigiani e professionisti.")],
   links=("Altre pagine", [("Preventivi Facili per idraulici", "/preventivi-facili/idraulici/"), ("Tutte le funzioni di Preventivi Facili", "/preventivi-facili/")]),
   ctat="Prova Preventivi Facili", ctad="Scaricala gratis e crea i primi 3 preventivi."),
  en=dict(
   title="Quotes for Electricians — Preventivi Facili", desc="App for electricians: create professional PDF quotes in 30 seconds from your phone, with VAT, logo and signature. Works offline, no monthly fees.",
   eyebrow="FOR ELECTRICIANS • PDF QUOTES", h1a="The electrical quote,", h1b="ready before you leave the site.",
   sub="Create a professional PDF quote in about 30 seconds from your phone, with VAT calculated, your logo and your signature. It works offline and your data stays on your device.",
   s1=("Built for people who work on site", "Less paperwork, fewer evenings at the computer.", [
      ("Right after the site visit", "The app generates the PDF and prepares a ready-made message: send it via WhatsApp, email or AirDrop while you are still with the client."),
      ("VAT and tax regimes", "Standard, flat-rate or pension-fund regime: taxable amount, taxes and totals are worked out without calculation errors."),
      ("Signature and stamp on every PDF", "Upload your signature or company stamp once and it appears on every quote, ready for the client's acceptance."),
      ("Client address book", "Recall a regular client's details with one tap and fill in the new quote on the fly."),
      ("Works without a signal", "In basements or on site you don't need coverage: data stays on your phone and no quote ends up on external servers."),
      ("Your logo, your look", "Add your logo and business details so the quote looks like your company.")]),
   ex=("Sample line items", "Illustrative example with made-up amounts, not a price list.",
       ["Description", "Qty", "Amount"],
       [("Electrical panel with circuit breakers", "1", "€480.00"), ("Socket or light points", "8", "€280.00"), ("Labor (hours)", "6", "€228.00")],
       [("Subtotal", "€988.00"), ("VAT 22%", "€217.36"), ("Total", "€1,205.36")]),
   faq=[("Can I use it for several clients and job sites?", "Yes. The client address book keeps your regular clients' details and you recall them with one tap when creating a new quote."),
        ("Is my clients' data safe?", "The app works with local-only storage on your phone: no external server collects your clients' names or your price lists."),
        ("How much does it cost?", "You can download it for free and create your first 3 quotes. To continue there is a one-time lifetime purchase with no monthly fees; the current price is shown in the store."),
        ("Is there a page for other trades?", "Yes, there is also a page for plumbers; it is the same app and works for tradespeople and freelancers.")],
   links=("More pages", [("Preventivi Facili for plumbers", "/preventivi-facili/idraulici/en/"), ("All Preventivi Facili features", "/preventivi-facili/en/")]),
   ctat="Try Preventivi Facili", ctad="Download it for free and create your first 3 quotes."),
  es=dict(
   title="Presupuestos para Electricistas — Preventivi Facili", desc="App para electricistas: crea presupuestos PDF profesionales en 30 segundos desde el móvil, con IVA, logo y firma. Funciona sin conexión, sin cuotas mensuales.",
   eyebrow="PARA ELECTRICISTAS • PRESUPUESTOS PDF", h1a="El presupuesto eléctrico,", h1b="listo antes de salir de la obra.",
   sub="Crea un presupuesto PDF profesional en unos 30 segundos desde el móvil, con IVA calculado, tu logo y tu firma. Funciona sin conexión y los datos se quedan en tu dispositivo.",
   s1=("Pensado para quien trabaja en obra", "Menos papeleo, menos tardes frente al ordenador.", [
      ("Justo después de la visita", "La app genera el PDF y prepara un mensaje listo: lo envías por WhatsApp, correo o AirDrop mientras sigues con el cliente."),
      ("IVA y regímenes fiscales", "Régimen general, a tanto alzado o con caja de previsión: base imponible, impuestos y totales se calculan sin errores de cuenta."),
      ("Firma y sello en cada PDF", "Cargas una vez tu firma o el sello de la empresa y aparecen en cada presupuesto, listos para la aceptación del cliente."),
      ("Agenda de clientes", "Recuperas los datos de un cliente habitual con un toque y rellenas el nuevo presupuesto al momento."),
      ("Funciona sin cobertura", "En sótanos o en obra no hace falta señal: los datos se quedan en tu móvil y ningún presupuesto acaba en servidores externos."),
      ("Tu logo, tu estilo", "Añade tu logo y los datos de tu empresa: el presupuesto tiene el aspecto de tu negocio.")]),
   ex=("Un ejemplo de conceptos", "Ejemplo ilustrativo con importes inventados, no una tarifa.",
       ["Descripción", "Cant.", "Importe"],
       [("Cuadro eléctrico con magnetotérmicos", "1", "480,00 €"), ("Puntos de enchufe o luz", "8", "280,00 €"), ("Mano de obra (horas)", "6", "228,00 €")],
       [("Base imponible", "988,00 €"), ("IVA 22%", "217,36 €"), ("Total", "1.205,36 €")]),
   faq=[("¿Puedo usarla con varios clientes y obras?", "Sí. La agenda de clientes guarda los datos de los clientes habituales y los recuperas con un toque al crear un nuevo presupuesto."),
        ("¿Los datos de mis clientes están seguros?", "La app funciona con almacenamiento solo local en tu móvil: ningún servidor externo recoge los nombres de tus clientes ni tus tarifas."),
        ("¿Cuánto cuesta?", "Puedes descargarla gratis y crear tus primeros 3 presupuestos. Para continuar hay una compra única de por vida, sin cuotas mensuales; el precio actualizado figura en la tienda."),
        ("¿Hay una página para otros oficios?", "Sí, también hay una página para fontaneros; es la misma app y sirve para profesionales y autónomos.")],
   links=("Otras páginas", [("Preventivi Facili para fontaneros", "/preventivi-facili/idraulici/es/"), ("Todas las funciones de Preventivi Facili", "/preventivi-facili/es/")]),
   ctat="Prueba Preventivi Facili", ctad="Descárgala gratis y crea tus primeros 3 presupuestos."),
 ),
 'pizzerie': dict(parent='foodlio', sub='pizzerie', name='Foodlio', icon='foodlio/icon.png',
  it=dict(
   title="Food Cost della Pizza e Margini — Foodlio", desc="Foodlio per pizzerie: calcola il food cost di ogni pizza, tieni aggiornati i prezzi degli ingredienti e proteggi i margini del menu su iOS e Android.",
   eyebrow="PER PIZZERIE • FOOD COST E MARGINI", h1a="Quanto costa davvero", h1b="una pizza, ingredienti compresi?",
   sub="Foodlio calcola il food cost di ogni ricetta, ricalcola tutto quando cambia il prezzo di farina, mozzarella o pomodoro e ti aiuta a decidere il prezzo giusto in menu.",
   s1=("Dalla ricetta al prezzo in menu", "Numeri chiari, senza fogli di calcolo.", [
      ("Ingredienti sempre aggiornati", "Cambi il prezzo di una materia prima una volta e il costo si aggiorna in tutte le ricette collegate."),
      ("Costo per porzione", "Ingredienti e quantità diventano costo della ricetta, food cost in percentuale e margine unitario."),
      ("Menu engineering", "Analizzi i piatti per popolarità e redditività: Stars, Plowhorses, Puzzles e Dogs."),
      ("Prezzo consigliato", "Indichi il food cost che vuoi raggiungere e Foodlio calcola il prezzo di vendita suggerito."),
      ("Report in PDF", "Esporti i numeri e li condividi con soci e collaboratori."),
      ("Valore del magazzino", "Tieni d'occhio il valore degli ingredienti in dispensa.")]),
   ex=("Come si calcola il food cost", "Esempio semplificato (IVA 10%): non include personale, affitto, energia e altri costi.",
       ["Voce", "Valore"],
       [("Costo degli ingredienti per pizza", "1,40 €"), ("Prezzo in menu (IVA 10% inclusa)", "8,50 €"), ("Prezzo al netto di IVA", "7,73 €")],
       [("Food cost", "18,1%"), ("Differenza prezzo − ingredienti", "6,33 €")]),
   faq=[("Come si calcola il food cost di una pizza?", "Si divide il costo degli ingredienti di una porzione per il prezzo di vendita al netto dell'IVA. Nell'esempio sopra: 1,40 € ÷ 7,73 € = 18,1%."),
        ("Qual è un food cost corretto?", "Non esiste un valore valido per tutti i locali: molti operatori usano circa il 30% come riferimento di partenza e lo adattano al proprio modello."),
        ("Il margine è l'utile?", "No. La differenza tra prezzo e costo degli ingredienti non include personale, affitto, energia, imposte e altri costi dell'attività."),
        ("Posso provarla prima di passare a Pro?", "Sì, puoi iniziare gratis con le prime ricette e i primi ingredienti. Le opzioni di acquisto sono mostrate nell'app.")],
   links=("Approfondisci", [("Tutte le funzioni di Foodlio", "/foodlio/"), ("Prova il calcolo nella home", "/#banco")]),
   ctat="Prova Foodlio", ctad="Inizia gratis con le prime ricette."),
  en=dict(
   title="Pizza Food Cost & Margins — Foodlio", desc="Foodlio for pizzerias: work out the food cost of every pizza, keep ingredient prices up to date and protect your menu margins on iOS and Android.",
   eyebrow="FOR PIZZERIAS • FOOD COST AND MARGINS", h1a="What does a pizza", h1b="really cost, ingredients included?",
   sub="Foodlio calculates the food cost of every recipe, recalculates everything when the price of flour, mozzarella or tomatoes changes, and helps you pick the right menu price.",
   s1=("From recipe to menu price", "Clear numbers, no spreadsheets.", [
      ("Always-updated ingredients", "Change a raw ingredient's price once and the cost updates across all linked recipes."),
      ("Cost per portion", "Ingredients and quantities become recipe cost, food cost percentage and unit margin."),
      ("Menu engineering", "Analyze dishes by popularity and profitability: Stars, Plowhorses, Puzzles and Dogs."),
      ("Target price suggestions", "Enter the food cost you want to reach and Foodlio works out the recommended selling price."),
      ("PDF reports", "Export your numbers and share them with partners and staff."),
      ("Inventory value", "Keep an eye on the value of the ingredients you have in stock.")]),
   ex=("How food cost is calculated", "Simplified example (10% VAT): it does not include staff, rent, energy or other costs.",
       ["Item", "Value"],
       [("Ingredient cost per pizza", "€1.40"), ("Menu price (10% VAT included)", "€8.50"), ("Price before VAT", "€7.73")],
       [("Food cost", "18.1%"), ("Price minus ingredients", "€6.33")]),
   faq=[("How do you calculate the food cost of a pizza?", "Divide the ingredient cost of one portion by the selling price before VAT. In the example above: €1.40 ÷ €7.73 = 18.1%."),
        ("What is a good food cost?", "There is no single value for every venue: many operators use about 30% as a starting reference and adjust it to their own model."),
        ("Is margin the same as profit?", "No. The difference between price and ingredient cost does not include staff, rent, energy, taxes or other business costs."),
        ("Can I try it before upgrading to Pro?", "Yes, you can start for free with your first recipes and ingredients. Purchase options are shown in the app.")],
   links=("Learn more", [("All Foodlio features", "/foodlio/en/"), ("Try the calculation on the home page", "/en/#banco")]),
   ctat="Try Foodlio", ctad="Start for free with your first recipes."),
  es=dict(
   title="Food Cost de la Pizza y Márgenes — Foodlio", desc="Foodlio para pizzerías: calcula el food cost de cada pizza, mantén actualizados los precios de los ingredientes y protege los márgenes de la carta en iOS y Android.",
   eyebrow="PARA PIZZERÍAS • FOOD COST Y MÁRGENES", h1a="¿Cuánto cuesta realmente", h1b="una pizza, ingredientes incluidos?",
   sub="Foodlio calcula el food cost de cada receta, lo recalcula todo cuando cambia el precio de la harina, la mozzarella o el tomate y te ayuda a decidir el precio justo en la carta.",
   s1=("De la receta al precio en carta", "Números claros, sin hojas de cálculo.", [
      ("Ingredientes siempre al día", "Cambias el precio de una materia prima una vez y el coste se actualiza en todas las recetas vinculadas."),
      ("Coste por ración", "Ingredientes y cantidades se convierten en coste de la receta, food cost en porcentaje y margen unitario."),
      ("Ingeniería de menú", "Analizas los platos por popularidad y rentabilidad: Estrellas, Caballos de batalla, Rompecabezas y Perros."),
      ("Precio recomendado", "Indicas el food cost que quieres alcanzar y Foodlio calcula el precio de venta sugerido."),
      ("Informes en PDF", "Exportas los números y los compartes con socios y colaboradores."),
      ("Valor del inventario", "Controlas el valor de los ingredientes que tienes en almacén.")]),
   ex=("Cómo se calcula el food cost", "Ejemplo simplificado (IVA 10%): no incluye personal, alquiler, energía ni otros costes.",
       ["Concepto", "Valor"],
       [("Coste de ingredientes por pizza", "1,40 €"), ("Precio en carta (IVA 10% incluido)", "8,50 €"), ("Precio sin IVA", "7,73 €")],
       [("Food cost", "18,1%"), ("Diferencia precio − ingredientes", "6,33 €")]),
   faq=[("¿Cómo se calcula el food cost de una pizza?", "Se divide el coste de los ingredientes de una ración entre el precio de venta sin IVA. En el ejemplo: 1,40 € ÷ 7,73 € = 18,1%."),
        ("¿Cuál es un food cost correcto?", "No existe un valor válido para todos los locales: muchos profesionales usan alrededor del 30% como referencia inicial y lo adaptan a su modelo."),
        ("¿El margen es el beneficio?", "No. La diferencia entre el precio y el coste de los ingredientes no incluye personal, alquiler, energía, impuestos ni otros costes del negocio."),
        ("¿Puedo probarla antes de pasar a Pro?", "Sí, puedes empezar gratis con las primeras recetas e ingredientes. Las opciones de compra se muestran en la app.")],
   links=("Más información", [("Todas las funciones de Foodlio", "/foodlio/es/"), ("Prueba el cálculo en la página de inicio", "/es/#banco")]),
   ctat="Prueba Foodlio", ctad="Empieza gratis con las primeras recetas."),
 ),
 'circoli': dict(parent='padel-match-manager', sub='circoli', name='Padel Match Manager', icon='padel-match-manager/icon.png',
  it=dict(
   title="Tornei Padel Americano e Mexicano — Padel Match Manager", desc="Organizza tornei di padel Americano e Mexicano nel tuo circolo: turni sui campi, punteggi e classifiche in tempo reale, anche offline. iOS e Android.",
   eyebrow="PER CIRCOLI E GRUPPI • TORNEI DI PADEL", h1a="Il torneo di padel del tuo circolo,", h1b="senza fogli e calcolatrice.",
   sub="Aggiungi i giocatori e Padel Match Manager distribuisce le partite sui campi disponibili, aggiorna la classifica dopo ogni match e funziona anche senza connessione o account.",
   s1=("Per chi organizza", "Più tempo a giocare, meno a fare turni.", [
      ("Americano e Mexicano", "Compagni a rotazione oppure abbinamenti dinamici in base ai punteggi in corso: scegli il ritmo del torneo."),
      ("Gironi e tabelloni", "Round Robin e tabelloni a eliminazione singola o doppia, per organizzare la competizione che hai in mente."),
      ("Turni automatici", "Inserisci i giocatori e le partite vengono distribuite sui campi disponibili con rotazioni equilibrate."),
      ("Classifiche in tempo reale", "Registri i punteggi direttamente dal campo e vedi subito la classifica aggiornata."),
      ("Condividi con il gruppo", "Invii calendario, classifiche e tabelloni ai partecipanti."),
      ("Funziona al 100% offline", "Gestisci i tornei al circolo anche senza connessione e senza creare un account.")]),
   ex=("Come funziona un Americano", "Descrizione generale del formato.",
       ["Elemento", "In breve"],
       [("Compagni", "Cambiano a ogni turno"), ("Classifica", "Individuale, in base ai punti totalizzati"), ("Esempio a 8 giocatori", "Con 2 campi si giocano 2 partite per turno; con 7 turni ognuno ha avuto tutti gli altri come compagno")],
       []),
   faq=[("Cos'è un torneo Americano?", "È un formato in cui i compagni cambiano a ogni turno e la classifica è individuale: ognuno accumula i punti delle partite giocate."),
        ("Che differenza c'è con il Mexicano?", "Nel Mexicano gli abbinamenti dei turni successivi dipendono dalla classifica in corso, così si affrontano giocatori di livello simile."),
        ("Serve una connessione al circolo?", "La gestione dei tornei funziona offline. Per scaricare l'app, effettuare acquisti o inviare contenuti serve invece una connessione."),
        ("È la stessa app di Padel Americano e Mexicano?", "Sì. Padel Match Manager è il progetto pubblicato sugli store anche con il nome Padel Americano e Mexicano.")],
   links=("Approfondisci", [("Tutte le funzioni di Padel Match Manager", "/padel-match-manager/"), ("Provalo nella home", "/#banco")]),
   ctat="Prova Padel Match Manager", ctad="Scarica l'app e organizza il tuo prossimo torneo."),
  en=dict(
   title="Padel Americano & Mexicano Tournaments — Padel Match Manager", desc="Organize Americano and Mexicano padel tournaments for your club: court rotations, scores and live standings, even offline. On iOS and Android.",
   eyebrow="FOR CLUBS AND GROUPS • PADEL TOURNAMENTS", h1a="Your club's padel tournament,", h1b="without paper sheets or a calculator.",
   sub="Add the players and Padel Match Manager spreads the matches across the available courts, updates the standings after every match and works without a connection or an account.",
   s1=("For organizers", "More time playing, less time doing rotations.", [
      ("Americano and Mexicano", "Rotating partners or dynamic pairings based on live scores: you set the tournament pace."),
      ("Groups and brackets", "Round Robin and single or double elimination brackets, to host the competition you have in mind."),
      ("Automatic rounds", "Enter the players and the matches are spread across the available courts with balanced rotations."),
      ("Live standings", "Log scores right from the court and see the updated standings straight away."),
      ("Share with the group", "Send the schedule, standings and brackets to the participants."),
      ("Works 100% offline", "Run tournaments at the club without a connection and without creating an account.")]),
   ex=("How an Americano works", "General description of the format.",
       ["Element", "In short"],
       [("Partners", "Change every round"), ("Standings", "Individual, based on total points scored"), ("Example with 8 players", "With 2 courts, 2 matches are played per round; over 7 rounds everyone has partnered with all the others")],
       []),
   faq=[("What is an Americano tournament?", "A format where partners change every round and the standings are individual: each player accumulates the points from the matches they play."),
        ("How is it different from Mexicano?", "In Mexicano, later pairings depend on the current standings, so players of a similar level face each other."),
        ("Do I need a connection at the club?", "Tournament management works offline. A connection is needed to download the app, make purchases or send content."),
        ("Is it the same app as Padel Americano e Mexicano?", "Yes. Padel Match Manager is the project published on the stores also under the name Padel Americano e Mexicano.")],
   links=("Learn more", [("All Padel Match Manager features", "/padel-match-manager/en/"), ("Try it on the home page", "/en/#banco")]),
   ctat="Try Padel Match Manager", ctad="Download the app and organize your next tournament."),
  es=dict(
   title="Torneos de Pádel Americano y Mexicano — Padel Match Manager", desc="Organiza torneos de pádel Americano y Mexicano en tu club: rotaciones en las pistas, resultados y clasificaciones en directo, incluso sin conexión. iOS y Android.",
   eyebrow="PARA CLUBES Y GRUPOS • TORNEOS DE PÁDEL", h1a="El torneo de pádel de tu club,", h1b="sin hojas ni calculadora.",
   sub="Añade a los jugadores y Padel Match Manager reparte los partidos en las pistas disponibles, actualiza la clasificación tras cada partido y funciona sin conexión ni cuenta.",
   s1=("Para quien organiza", "Más tiempo jugando, menos haciendo rotaciones.", [
      ("Americano y Mexicano", "Compañeros rotativos o emparejamientos dinámicos según los resultados en curso: tú eliges el ritmo del torneo."),
      ("Grupos y cuadros", "Liguillas Round Robin y cuadros de eliminación simple o doble, para organizar la competición que tienes en mente."),
      ("Rondas automáticas", "Introduce los jugadores y los partidos se reparten en las pistas disponibles con rotaciones equilibradas."),
      ("Clasificaciones en directo", "Registras los resultados desde la pista y ves al instante la clasificación actualizada."),
      ("Comparte con el grupo", "Envía el calendario, las clasificaciones y los cuadros a los participantes."),
      ("Funciona 100% sin conexión", "Gestiona los torneos en el club sin conexión y sin crear una cuenta.")]),
   ex=("Cómo funciona un Americano", "Descripción general del formato.",
       ["Elemento", "En breve"],
       [("Compañeros", "Cambian en cada ronda"), ("Clasificación", "Individual, según los puntos totales"), ("Ejemplo con 8 jugadores", "Con 2 pistas se juegan 2 partidos por ronda; con 7 rondas cada uno ha jugado con todos los demás como compañero")],
       []),
   faq=[("¿Qué es un torneo Americano?", "Es un formato en el que los compañeros cambian en cada ronda y la clasificación es individual: cada jugador acumula los puntos de los partidos que juega."),
        ("¿En qué se diferencia del Mexicano?", "En el Mexicano, los emparejamientos de las rondas siguientes dependen de la clasificación en curso, así se enfrentan jugadores de nivel similar."),
        ("¿Hace falta conexión en el club?", "La gestión de torneos funciona sin conexión. Para descargar la app, hacer compras o enviar contenido sí hace falta conexión."),
        ("¿Es la misma app que Padel Americano e Mexicano?", "Sí. Padel Match Manager es el proyecto publicado en las tiendas también con el nombre Padel Americano e Mexicano.")],
   links=("Más información", [("Todas las funciones de Padel Match Manager", "/padel-match-manager/es/"), ("Pruébalo en la página de inicio", "/es/#banco")]),
   ctat="Prueba Padel Match Manager", ctad="Descarga la app y organiza tu próximo torneo."),
 ),
}
